version: '3'
services:
  backend-argent:
    build: ./backend/build/docker/
    ports:
    - "9000:9000"
  db:
    image: postgres
    ports:
    - "9898:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  frontend:
    build: ./webclient/docker
    depends_on:
    - backend-argent
    ports:
    - "8080:80"
